#! /usr/bin/env bash

SESSIONNAME=irc

urxvt -name irc -e ssh -R 2222:localhost:22 nafai@travishartwell.net -t \
     "TERM=screen-256color; SESSIONNAME=irc; tmux attach-session -t $SESSIONNAME || tmux new-session -s $SESSIONNAME"
